[default]
solc_version = "0.8.0"
sender='0xdAaA1Ba6839a7F04061dA8805De5800B152Def2F'
tx_origin='0xdAaA1Ba6839a7F04061dA8805De5800B152Def2F'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 1
optimizer = true
optimizer_runs = 200

[ci]
fuzz-runs = 10_000
